# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eead362455ba154b05ec67ec81598006856b56c4c96581d61f62acb6d6479f68e4bfad52583b9e4330ee15589070b2a9e9e4635c563094dd6e9c4843e4df5f3a

test:
  secret_key_base: 0b72b40ba5b792f2f3be830274b25ce1dc24358a0b24a98c1adcbc6bd1e992799a7bd7aed1257b40d425772dbd10daf763b0b26dc389168d78f915e783b47791

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
